name: Python Tests with pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu for the test runner
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]  # Test across multiple Python versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Check out the code from the repository

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3  # Set up the Python environment
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install pandas yfinance pytest
        pip install pytest

    - name: Run tests with pytest
      run: |
        export PYTHONPATH=$(pwd)/src
        pytest  -v # Run pytest to execute the tests

    - name: Upload test results to GitHub Actions
      if: success()  # Upload only if tests are successful
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./test-reports
